# Generated by Django 5.1.5 on 2025-01-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True, unique=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('profile_picture', models.URLField(null=True)),
                ('contact_number', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
