# Generated by Django 5.1.5 on 2025-01-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
