# Generated by Django 5.1.5 on 2025-01-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_alter_userblogs_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblogs',
            name='status',
            field=models.CharField(default='True', max_length=100, null=True),
        ),
    ]
